### Python version

In [1]:
!python --version

Python 3.10.14

In [2]:
!pip list

Package           Version
----------------- -----------
appnope           0.1.4
asttokens         2.4.1
async-timeout     4.0.3
cffi              1.17.1
comm              0.2.2
cryptography      43.0.1
debugpy           1.8.5
decorator         5.1.1
dnspython         2.6.1
exceptiongroup    1.2.2
executing         2.1.0
ipykernel         6.29.5
ipython           8.27.0
jedi              0.19.1
jupyter_client    8.6.3
jupyter_core      5.7.2
matplotlib-inline 0.1.7
nest-asyncio      1.6.0
numpy             2.1.1
packaging         24.1
pandas            2.2.2
parso             0.8.4
pexpect           4.9.0
pip               23.0.1
platformdirs      4.3.6
prompt_toolkit    3.0.47
psutil            6.0.0
ptyprocess        0.7.0
pure_eval         0.2.3
pycparser         2.22
Pygments          2.18.0
pymongo           4.8.0
PyMySQL           1.1.1
python-dateutil   2.9.0.post0
python-dotenv     1.0.1
pytz              2024.2
pyzmq             26.2.0
redis             5.0.8
setuptools        65.5.0
six               1.16.0
stack-data        0.6.3
tornado           6.4.1
traitlets         5.14.3
typing_extensions 4.12.2
tzdata            2024.1
wcwidth           0.2.13

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip

### Install library

In [5]:
# Environment
%pip install python-dotenv
%pip install cryptography
%pip install pandas

Requirement already satisfied: python-dotenv in /Users/eastsea/.pyenv/versions/3.10.14/envs/dev-env/lib/python3.10/site-packages (1.0.1)

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: cryptography in /Users/eastsea/.pyenv/versions/3.10.14/envs/dev-env/lib/python3.10/site-packages (43.0.1)
Requirement already satisfied: cffi>=1.12 in /Users/eastsea/.pyenv/versions/3.10.14/envs/dev-env/lib/python3.10/site-packages (from cryptography) (1.17.1)
Requirement already satisfied: pycparser in /Users/eastsea/.pyenv/versions/3.10.14/envs/dev-env/lib/python3.10/site-packages (from cffi>=1.12->cryptography) (2.22)

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Collecting pandas
  Downloading pandas-2.2.2-cp310-cp310-macosx_11_0_arm64.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 45.0 MB/s eta 0:00:0000:010:01
Collecting pytz>=2020.1
  Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.0/508.0 kB 41.3 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/eastsea/.pyenv/versions/3.10.14/envs/dev-env/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Collecting tzdata>=2022.7
  Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 34.5 MB/s eta 0:00:00
Collecting numpy>=1.22.4
  Downloading numpy-2.1.1-cp310-cp310-macosx_14_0_arm64.whl (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 43.7 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: six>=1.5 in /Users/eastsea/.pyenv/versions/3.10.14/envs/dev-env/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.1.1 pandas-2.2.2 pytz-2024.2 tzdata-2024.1

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [25]:
# MySQL
%pip install PyMySQL

Requirement already satisfied: PyMySQL in /Users/eastsea/.pyenv/versions/3.10.14/envs/dev-env/lib/python3.10/site-packages (1.1.1)

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [26]:
# MongoDB
%pip install pymongo

Requirement already satisfied: pymongo in /Users/eastsea/.pyenv/versions/3.10.14/envs/dev-env/lib/python3.10/site-packages (4.8.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /Users/eastsea/.pyenv/versions/3.10.14/envs/dev-env/lib/python3.10/site-packages (from pymongo) (2.6.1)

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [27]:
# Redis
%pip install redis

Requirement already satisfied: redis in /Users/eastsea/.pyenv/versions/3.10.14/envs/dev-env/lib/python3.10/site-packages (5.0.8)
Requirement already satisfied: async-timeout>=4.0.3 in /Users/eastsea/.pyenv/versions/3.10.14/envs/dev-env/lib/python3.10/site-packages (from redis) (4.0.3)

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

### Preload

In [3]:
from dotenv import load_dotenv

LOCAL_HOST = "127.0.0.1"
load_dotenv()

True

## MySQL Query

In [6]:
import os
import pymysql
import pandas as pd

mysql_conn = pymysql.connect(
    host=LOCAL_HOST,
    user=os.getenv("MYSQL_USER"),
    password=os.getenv("MYSQL_PASSWORD"),
    database=os.getenv("MYSQL_DATABASE"),
    port=3306,
    charset="utf8mb4",
    cursorclass=pymysql.cursors.DictCursor,
)

In [9]:
cursor = mysql_conn.cursor()

query = """
select *
from test_table
"""

cursor.execute(query)
result = cursor.fetchall()

df = pd.DataFrame(result)
df

   no   name              email gender  age
0   1  user1  user1@example.com      M   26
1   2  user2  user2@example.com      M   35
2   3  user3  user3@example.com      F   17

In [ ]:
-- SQL Example
show tables;

create table test_table (
    no int(11) not null auto_increment,
    name varchar(20) not null,
    email varchar(100),
    gender char(1),
    age int(3),
    constraint test_table_pk primary key (no)
);

describe test_table;

insert into test_table value (null, 'user1', 'user1@example.com', 'M', 26);
insert into test_table value (null, 'user2', 'user2@example.com', 'M', 35);
insert into test_table value (null, 'user3', 'user3@example.com', 'F', 17);

select *
from test_table;

## MongoDB Query

In [10]:
import os
import pymongo
import pandas as pd

mongo_client = pymongo.MongoClient(f"mongodb://{os.getenv('MONGO_INITDB_ROOT_USERNAME')}:{os.getenv('MONGO_INITDB_ROOT_PASSWORD')}@{LOCAL_HOST}:27017/")
db = mongo_client[os.getenv("MONGO_INITDB_DATABASE")]
collection = db["test_table"]

In [12]:
data = collection.find({})

df = pd.DataFrame(list(data))
df

                        _id   name              email gender  age
0  668a74da9c7c98546d3ace3b  user1  user1@example.com      M   26
1  668a74da9c7c98546d3ace3c  user2  user2@example.com      M   35
2  668a74da9c7c98546d3ace3d  user3  user3@example.com      F   17

In [ ]:
-- SQL Example
show dbs

use mygodis_db

db.createCollection("test_table");

show collections

db.test_table.insertOne({"name": "user1", "email": "user1@example.com", "gender": "M", "age": 26});
db.test_table.insertOne({"name": "user2", "email": "user2@example.com", "gender": "M", "age": 35});
db.test_table.insertOne({"name": "user3", "email": "user3@example.com", "gender": "F", "age": 17});

db.test_table.find();

## Redis Query

In [23]:
import json
import redis
import pandas as pd

redis_conn = redis.Redis(
    host=LOCAL_HOST,
    port=6379,
    decode_responses=True,
)

In [24]:
keys = redis_conn.keys("*")
data = redis_conn.mget(keys)

data = [json.loads(item) for item in data]

df = pd.DataFrame(data)
df

    name              email gender  age
0  user2  user2@example.com      M   35
1  user3  user3@example.com      F   17
2  user1  user1@example.com      M   26

In [ ]:
-- SQL Example
keys *

set test_user1 '{"name": "user1", "email": "user1@example.com", "gender": "M", "age": 26}'
set test_user2 '{"name": "user2", "email": "user2@example.com", "gender": "M", "age": 35}'
set test_user3 '{"name": "user3", "email": "user3@example.com", "gender": "F", "age": 17}'

get test_user1
mget test_user1 test_user2 test_user3